### ISSUE TITLE
How to set a list of views without the pair number?

### ISSUE THREAD

**Issue by AndrexOfficial** [izqui/SHSidebarController#1]
I'm trying to make a clean list menu with views inside, but I can't do it? can you write down how to do it?

**Comment by izqui** [comment]
You can do it just allocating and creating the ViewController and then cretaing the dictionary with the title and the VC

**Comment by AndrexOfficial** [comment]
Can you write down an example? Thanks
For example i have 3 Views (HomeViewController, NewsViewController and GalleryViewController)
How can I order them and make a simple and clean list.
1) Home
2) News
3) Gallery

Thanks :)

**Comment by izqui** [comment]
NSMutableArray *viewsArray = [NSMutableArray array];

HomeViewController *h = [[home…
UINavigationController *nav = [[UINav..] withRootViewController:h];
NSDictionary *dict = [[nsdic…] initWithObjectsAndKeys:@"Home", @"title", nav, @"vc", nil];

[viewsArray addObject:dict];

(…) Do this with each view

And then you pass that array to SHSidebarController.  

Hope it helped  

## 

Jorge Izquierdo

Developer

<a href="http://i (http://showyapp.com/user/Jorge)zqui.me">Blog</a> | <a href="http://showyapp.com/user/Jorge">My Showy</a> | <a href="http://twitter.com/izqui9">Twitter</a>

Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by AndrexOfficial** [comment]
I wrote this code, but I only see 5 items with the same view (Home) 

this is my code:

NSMutableArray *vcs = [NSMutableArray array];

```
RedVC *red = [[RedVC alloc] init];

UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:red];

NSDictionary *view = [NSDictionary dictionaryWithObjectsAndKeys:nav, @"vc", [NSString stringWithFormat:@"Home"], @"title", nil];
[vcs addObject:view];


RootViewController *blue = [[RootViewController alloc] init];

UINavigationController *nav1 = [[UINavigationController alloc] initWithRootViewController:blue];

NSDictionary *view1 = [NSDictionary dictionaryWithObjectsAndKeys:nav, @"vc", [NSString stringWithFormat:@"News"], @"title", nil];
[vcs addObject:view];

ReaderDemoController *PDF = [[ReaderDemoController alloc] init];

UINavigationController *nav2 = [[UINavigationController alloc] initWithRootViewController:PDF];

NSDictionary *view2 = [NSDictionary dictionaryWithObjectsAndKeys:nav, @"vc", [NSString stringWithFormat:@"PDF"], @"title", nil];
[vcs addObject:view];

SpringViewController *menuextra = [[SpringViewController alloc] init];

UINavigationController *nav3 = [[UINavigationController alloc] initWithRootViewController:menuextra];

NSDictionary *view3 = [NSDictionary dictionaryWithObjectsAndKeys:nav, @"vc", [NSString stringWithFormat:@"Menu"], @"title", nil];
[vcs addObject:view];

GareViewController *garelista = [[GareViewController alloc] init];

UINavigationController *nav4 = [[UINavigationController alloc] initWithRootViewController:garelista];

NSDictionary *view4 = [NSDictionary dictionaryWithObjectsAndKeys:nav, @"vc", [NSString stringWithFormat:@"Calendario Gare"], @"title", nil];
[vcs addObject:view];


//Create controller and set views
SHSidebarController *sidebar = [[SHSidebarController alloc] initWithArrayOfVC:vcs];
self.window.rootViewController = sidebar;
```

**Comment by AndrexOfficial** [comment]
fixed the problem by myself! :) 
Thanks
