### ISSUE TITLE
App crashes on ios5.1

### ISSUE THREAD

**Issue by lalith-b** [izqui/SHSidebarController#3]
Please find the log below.

Example[538:f803] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AppDelegate setWindow:]: unrecognized selector sent to instance 0x6893b30'

to fix this add "@synthesize window";

in implementation of AppDelegate

**Comment by izqui** [comment]
Need to use Xcode 4.5 or synthesize the window in appdelegate

## 

Jorge Izquierdo

Developer

<a href="http://i (http://showyapp.com/user/Jorge)zqui.me">Blog</a> | <a href="http://showyapp.com/user/Jorge">My Showy</a> | <a href="http://twitter.com/izqui9">Twitter</a>

Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
