### ISSUE TITLE
How to put left images in cells?

### ISSUE THREAD

**Issue by anthonyguay** [izqui/SHSidebarController#9]
Error

**Comment by izqui** [comment]
If you want to, make a push request and I'll see what I can do :)

## 

Jorge Izquierdo

Developer

Blog: http://izqui.me
Twitter: http://twitter.com/izqui9
MyShowy: http://showyapp.com/user/Jorge

Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by izqui** [comment]
Pull request*
—
